CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('Male', 'Female') NOT NULL,
    age INT NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    home_address TEXT NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    contact_number VARCHAR(15) NOT NULL,
    secondary_contact VARCHAR(15),
    email VARCHAR(100) NOT NULL,
    guardian_first_name VARCHAR(50) NOT NULL,
    guardian_middle_name VARCHAR(50),
    guardian_last_name VARCHAR(50) NOT NULL,
    relationship VARCHAR(20) NOT NULL,
    guardian_contact VARCHAR(15) NOT NULL,
    guardian_email VARCHAR(100),
    previous_school VARCHAR(100) NOT NULL,
    grade_completed VARCHAR(20) NOT NULL,
    school_year_completed VARCHAR(10) NOT NULL,
    gpa VARCHAR(5),
    track VARCHAR(50) NOT NULL,
    strand VARCHAR(50),
    grade_level VARCHAR(20) NOT NULL,
    class_schedule VARCHAR(20) NOT NULL,
    additional_notes TEXT,
    medical_info TEXT,
    special_accommodations TEXT,
    payment_amount DECIMAL(10, 2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    receipt_number VARCHAR(20) NOT NULL,
    profile_picture VARCHAR(255),
    transcript VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);